
---
- name: sample 
  hosts: localhost
  connection: local
  vars:
    # Variable parameters
    vplexhost: '10.228.69.177'
    vplexuser: 'service'
    vplexpassword: 'Mi@Dim7T'
    cluster_name: 'cluster-1'
    # Constant parameters
    verifycert: false
    a_list: ['1','2','3','4','5','6','7','8']
    list_three: []

  tasks:
#    - name: list
#      set_fact:
#        a_list: '{{a_list}} + [{{item}}]'
#      loop: "{{ range(0,9)|list }}"
#    - debug:
#        msg: "{{ a_list }}"

    - debug:
        msg: "{{a_list}}"
          
    - name: length
      set_fact:
        leng: "{{a_list|length}}"
    
    - name: l2
      set_fact:
        a_list: "{{a_list|difference(a_list[leng|int-1])}}"
      when: "{{leng}}%2 != 0"

    - name: l3
      set_fact:
        list_three: "{{list_three}} + [['{{a_list[item]}}','{{a_list[item+1]}}']]"
      loop: "{{ range(0,a_list|length,2)|list }}"

    - debug:
        msg: "{{list_three}}"
